\c books_project;

INSERT INTO books (title, published_year, author, description, category, is_favorite, uri) VALUES
('Remeberber Me', '2008', 'Sophie kinsella','Lexi wakes up in a hospital bed after a car accident, thinking it`s 2004 and she`s a twenty-five-year old with crooked teeth and a disastrous love life. But, to her disbelief, she learns it`s actually 2007 - she`s twenty-eight, her teeth are straight, she`s the boss of her department - and she`s married!', 'Romance', true, 'https://photos-us.bazaarvoice.com/photo/2/cGhvdG86YmFybmVzYW5kbm9ibGU/c2bfa944-3062-5745-ae17-b1ba65c8dbd5'),
('Someday, Someday', '2010', 'Marian Keyes','Anna Kennedy is a single, thirty-something woman living in Dublin who is looking for love, but is unlucky in that department.', 'Romance', false, 'https://photos-us.bazaarvoice.com/photo/2/cGhvdG86YmFybmVzYW5kbm9ibGU/f7d00f9d-9eb9-5b26-bc7f-8c1edb7e6e71'),
('The Secret Dreamworld of a Shopaholic', '2000', 'Sophie Kinsella','Rebecca Bloomwood is a financial journalist who is good at her job, but has a bad habit of shopping.', 'Comedy', true, 'https://photos-us.bazaarvoice.com/photo/2/cGhvdG86YmFybmVzYW5kbm9ibGU/6d38c6b7-6a1f-5d2b-9a01-9dc9c844ab67'),
('The One', '2018', 'John Marrs','A new dating app, The One, can match you with your soulmate based on DNA. But what happens when that match is someone you already know?', 'Thriller', false, 'https://photos-us.bazaarvoice.com/photo/2/cGhvdG86YmFybmVzYW5kbm9ibGU/efc6e383-6a1f-5d2b-9a01-9dc9c844ab67'),
('The Nightingale', '2015', 'Kristin Hannah','Two sisters in Nazi-occupied France must navigate the dangers of war and find ways to survive.', 'Historical Fiction', true, 'https://photos-us.bazaarvoice.com/photo/2/cGhvdG86YmFybmVzYW5kbm9ibGU/47a2b3dc-b3c3-5a74-9d5c-a5f08a1e5e71'),
('The Immortal Life of Henrietta Lacks', '2010', 'Rebecca Skloot','Henrietta Lacks was an African American woman whose cancer cells were taken without her knowledge in 1951 and became one of the most important cell lines in medical history.', 'Non-Fiction', false, 'https://photos-us.bazaarvoice.com/photo/2/cGhvdG86YmFybmVzYW5kbm9ibGU/fa7a00fa-b3c3-5a74-9d5c-a5f08a1e5e71');

